// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/blck-snwmn/grpc-sample/processor (interfaces: ProcessorClient)

// Package mock_processor is a generated GoMock package.
package mock_processor

import (
	context "context"
	processor "github.com/blck-snwmn/grpc-sample/processor"
	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
	reflect "reflect"
)

// MockProcessorClient is a mock of ProcessorClient interface
type MockProcessorClient struct {
	ctrl     *gomock.Controller
	recorder *MockProcessorClientMockRecorder
}

// MockProcessorClientMockRecorder is the mock recorder for MockProcessorClient
type MockProcessorClientMockRecorder struct {
	mock *MockProcessorClient
}

// NewMockProcessorClient creates a new mock instance
func NewMockProcessorClient(ctrl *gomock.Controller) *MockProcessorClient {
	mock := &MockProcessorClient{ctrl: ctrl}
	mock.recorder = &MockProcessorClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockProcessorClient) EXPECT() *MockProcessorClientMockRecorder {
	return m.recorder
}

// RegisterProcess mocks base method
func (m *MockProcessorClient) RegisterProcess(arg0 context.Context, arg1 *processor.Process, arg2 ...grpc.CallOption) (*processor.RegisteredMessage, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RegisterProcess", varargs...)
	ret0, _ := ret[0].(*processor.RegisteredMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterProcess indicates an expected call of RegisterProcess
func (mr *MockProcessorClientMockRecorder) RegisterProcess(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterProcess", reflect.TypeOf((*MockProcessorClient)(nil).RegisterProcess), varargs...)
}

// RequestNotification mocks base method
func (m *MockProcessorClient) RequestNotification(arg0 context.Context, arg1 *processor.NotificationRequest, arg2 ...grpc.CallOption) (processor.Processor_RequestNotificationClient, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RequestNotification", varargs...)
	ret0, _ := ret[0].(processor.Processor_RequestNotificationClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestNotification indicates an expected call of RequestNotification
func (mr *MockProcessorClientMockRecorder) RequestNotification(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestNotification", reflect.TypeOf((*MockProcessorClient)(nil).RequestNotification), varargs...)
}
